spring:
  datasource:
    url: jdbc:h2:file:./h2/sbzdb;DB_CLOSE_DELAY=-1
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.H2Dialect
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
  h2:
    console:
      enabled: true
      path: /h2

server:
  port: 8080

logging:
  level:
    org.springframework.security: DEBUG 

app:
  jwt:
    secret: replace-with-a-long-random-secret-at-least-32-characters
    expires-in-seconds: 86400
